### ISSUE TITLE
Add to the "Ultimate Beamer Theme List"

### ISSUE THREAD

**Issue by koppor** [jolars/moloch#15]
The  [Ultimate Beamer Theme List](https://github.com/martinbjeldbak/ultimate-beamer-theme-list) is a great resource for beamer themes. This theme should be added to there. With a good screenshot :)

**Comment by jolars** [comment]
Thanks for the suggestion! I've filed the PR: https://github.com/martinbjeldbak/ultimate-beamer-theme-list/pull/47

**Comment by samcarter** [comment]
@jolars  Maybe you could also make a PR for https://github.com/UweZiegenhagen/LaTeX-Beamer-Theme-Overview ?
