### ISSUE TITLE
Compilation error with Beamer class option `usepdftitle=false`

### ISSUE THREAD

**Issue by jpcirrus** [jolars/moloch#25]
First, many thanks for your work in taking Metropolis forward.

When the Beamer class option `usepdftitle=false` is set, then compilation fails. The reason is that in `beamerinnerthememoloch.sty`, in the definition of `\setbeamertemplate{title page}` the command `\beamer@andstripped` is used, which is defined at `beamerbasetitle.sty:151`, but only when `\ifbeamer@autopdfinfo` is `true`, which it isn't when `usepdftitle=false`.

Not sure if this should be changed in Moloch or Beamer.
cc @samcarter

**Comment by jpcirrus** [comment]
Thanks @samcarter that resolves the issue.

**Comment by jolars** [comment]
Hm, thanks for the report. I guess there's no point in working around this in moloch now that the command will be available in future beamer versions anyway.
